### ISSUE TITLE
COBezierTableView.swift crash if indexPathsForVisibleRows is nil

### ISSUE THREAD

**Issue by DrBeak1** [knutigro/COBezierTableView#11]
The exception `Fatal error: unexpectedly found nil while unwrapping an Optional values` occurs if `indexPathsForVisibleRows` is nil in COBezierTableView.swift. I solved this by doing a simple check on the object before trying to access it.

```
    if indexPathsForVisibleRows != nil {
        ....
    }
```

**Comment by knutigro** [comment]
Thanks @DrBeak1 :+1:
