### ISSUE TITLE
Protection level issues with Swift 3

### ISSUE THREAD

**Issue by BenSullivan-iOS** [knutigro/COBezierTableView#13]
I am trying to initialise my own path using "UIView.BezierPoints.p1 = CGPoint(x: 0, y: 0)" but I am receiving the error "p1 is unaccessible due to 'internal' protection level.

Do you have a solution to this? Thanks!

**Comment by benskill** [comment]
It

**Comment by BenSullivan-iOS** [comment]
It appears the properties within an public extension are internal by default so they need to be made public to access.

```
public extension UIView {

public struct BezierPoints {

 public static var p1 = CGPoint.zero
 public static var p2 = CGPoint.zero
 public static var p3 = CGPoint.zero
 public static var p4 = CGPoint.zero
}
```

**Comment by knutigro** [comment]
Great thanks! 👍
