### ISSUE TITLE
how bezierInterpolation is being calculated 

### ISSUE THREAD

**Issue by ihomam** [knutigro/COBezierTableView#5]
Hej :) thanx for this awesome controller 
I wonder if you explain the logic for me behind bezierInterpolation(t:, a:, b:, c:, d:)
if you could please give me a link so i can read more about this calculation or is it something you created?
return a + (-a \* 3 + t \* (3 \* a - a \* t)) \* t
            + (3 \* b + t \* (-6 \* b + b \* 3 \* t)) \* t
            + (c \* 3 - c \* 3 \* t) \* t2
            + d \* t3

**Comment by knutigro** [comment]
hi @ihomam: I have to admit that I dont understand the underlaying mathematics myselves ;-) As a startingpoint for COBezierTableView I did use code from this discussion thread: http://stackoverflow.com/questions/4089443/find-the-tangent-of-a-point-on-a-cubic-bezier-curve-on-an-iphone  Maybe you can find som explanation there?

**Comment by ihomam** [comment]
thanx Knutigro,  that's awesome :) 
-> checking the link
