### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Mrshj** [knutigro/COBezierTableView#9]

**Comment by Mrshj** [comment]
hi what can i do for you ?

**Comment by Mrshj** [comment]
oh my god , I'm really like COBezierTableView ，but I am not good at Swift ,I used it by OC so it's not very convenient， but I will learn Swift .. hha

**Comment by knutigro** [comment]
Hi. Nice to hear from you. Do you still use this control your Objective-C app? Yes, you should definitively learn swift! It's good to know if you want to continue make apps for iOS.

**Comment by Mrshj** [comment]
The last APP used.
